### ISSUE TITLE
vuepress2中使用打包后会报错

### ISSUE THREAD

**Issue by liub1934** [nonzzz/vite-bundle-analyzer#43]
### Describe the issue

报错内容如下所示：
![image](https://github.com/user-attachments/assets/06879d27-4143-4bea-9de0-68546f506693)
```
error [vite-bundle-anlyzer] Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at new eX (file:///Users/bing/Documents/Code/liubing.me/node_modules/.pnpm/vite-bundle-analyzer@0.13.0/node_modules/vite-bundle-analyzer/dist/index.mjs:1:18084)
    at file:///Users/bing/Documents/Code/liubing.me/node_modules/.pnpm/vite-bundle-analyzer@0.13.0/node_modules/vite-bundle-analyzer/dist/index.mjs:1:19121
    at e3.setup (file:///Users/bing/Documents/Code/liubing.me/node_modules/.pnpm/vite-bundle-analyzer@0.13.0/node_modules/vite-bundle-analyzer/dist/index.mjs:1:19255)
    at e4.addModule (file:///Users/bing/Documents/Code/liubing.me/node_modules/.pnpm/vite-bundle-analyzer@0.13.0/node_modules/vite-bundle-analyzer/dist/index.mjs:1:21266)
    at Object.generateBundle (file:///Users/bing/Documents/Code/liubing.me/node_modules/.pnpm/vite-bundle-analyzer@0.13.0/node_modules/vite-bundle-analyzer/dist/index.mjs:1:24042)
    at file:///Users/bing/Documents/Code/liubing.me/node_modules/.pnpm/rollup@4.25.0/node_modules/rollup/dist/es/shared/node-entry.js:20807:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.
```

下面是我的运行环境

```
  System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 397.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.15.8 - ~/.nvm/versions/node/v18.19.0/bin/pnpm
```

### Expected behavior

能够成功生成文件

### Steps to reproduce

这个是我的代码仓库：https://github.com/liub1934/liubing.me

1. pnpm安装vite-bundle-analyzer
2. 在`src/.vuepress/configs/vite.config.ts`中plugins中新增配置
![image](https://github.com/user-attachments/assets/e9287139-6388-4058-ae2e-876fec531ee5)
```
analyzer({
      analyzerMode: 'static',
      fileName: 'report.html',
 })
```
3. 运行pnpm docs:build

**Comment by nonzzz** [comment]
我已经发布了`v0.13.1`我认为它能解决这个问题 但是`vitpress` 在构建阶段会共享插件实例,而插件本身是极度依赖`sourcemap`这个功能用来确保最终的体积分析。我也在`README.md`说明了一些情况。但是我不确定为什么`vitepress`会删除一些产物。因此我建议给`analyzeMode`设置为`server`。尽管会生成2份一样的报告服务。但是对于大部分ssr框架这2个报告都应该不同。没有理由单独对vitepress做特定修复

**Comment by nonzzz** [comment]
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/f2663ab4-6be5-4403-bb64-fafddd5e50f3">
<img width="1511" alt="image" src="https://github.com/user-attachments/assets/700de0f8-1878-4684-870c-32a66b20d9a1">
